spring:
  application:
    name: thespace

#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "true"
    show-sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: webuser
    password: webuser
    url: jdbc:mariadb://localhost:3307/thespace

logging:
  level:
    com:
      thespace:
        thespace: trace
        springframework: trace


