spring:
  application:
    name: thespace

  servlet:
    multipart:
      enabled: true
      max-file-size: "100MB"
      max-request-size: "300MB"
      location: "/static/files/"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "true"
    show-sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: webuser
    password: webuser
    url: jdbc:mariadb://localhost:3307/thespace

logging:
  level:
    com:
      thespace:
        thespace: trace
        springframework: trace


com:
  thespace:
    upload:
      path: src/main/resources/static/files
